name: Create PRs from develop to release
on:
  push:
    branches:
      - develop
jobs:
  git-pr-release:
    name: git-pr-release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: develop

    - name: Create PR to sync changes for Prep
      uses: bakunyo/git-pr-release-action@master
      env:
        TZ: "Asia/Tokyo"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: release
        GIT_PR_RELEASE_BRANCH_STAGING: develop
        GIT_PR_RELEASE_TEMPLATE: '.github/config/.git-pr-prep-template'
