name: Create PRs from release branch
on:
  push:
    branches:
      - release
jobs:
  git-pr-release-to-main:
    name: git-pr-release-to-main
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        ref: release

    - name: Create Release PR to main
      uses: bakunyo/git-pr-release-action@master
      env:
        TZ: "Asia/Tokyo"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: main
        GIT_PR_RELEASE_BRANCH_STAGING: release
        GIT_PR_RELEASE_TEMPLATE: '.github/config/.git-pr-release-template'
        GIT_PR_RELEASE_LABELS: 'releases'

  git-pr-release-to-develop:
    name: git-pr-release-to-develop
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        ref: release

    - name: Create Back-merge PR to develop
      uses: bakunyo/git-pr-release-action@master
      env:
        TZ: "Asia/Tokyo"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: develop
        GIT_PR_RELEASE_BRANCH_STAGING: release
        GIT_PR_RELEASE_TEMPLATE: '.github/config/.git-pr-backmerge-template'
