name: Release Please

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # token: default is ${{ github.token }}
          config-file: '.github/config/release-please-config.json'
          manifest-file: .release-please-manifest.json
          target-branch: 'release'
