name: Release Please

on:
  push:
    branches:
      # - main
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
