name: Sync commit diff to PRs

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  sync-commit-messages:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v5

      # https://github.com/technote-space/pr-commit-body-action/tree/main
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
